/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogos;

import dao.ArticulosDao;
import dao.ProveedoresDao;
import datos.Articulo;
import datos.Proveedor;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author joshua
 */
public class eliminandoProveedor extends javax.swing.JDialog {

    private List<Articulo> arts;
    private Proveedor provElim;

    /**
     * Creates new form eliminandoProveedor
     */
    public eliminandoProveedor(java.awt.Frame parent, boolean modal, List<Articulo> listArts, Proveedor prov) {
        super(parent, modal);
        initComponents();
        this.arts = listArts;
        this.provElim = prov;
    }

    private eliminandoProveedor(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarga = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        lblArticulo = new javax.swing.JLabel();
        cmdVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(278, 145));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga.gif"))); // NOI18N
        getContentPane().add(lblCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 12, -1, 37));
        getContentPane().add(barraProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 249, -1));
        getContentPane().add(lblArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, 249, 20));

        cmdVolver.setText("Volver");
        cmdVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVolverActionPerformed(evt);
            }
        });
        getContentPane().add(cmdVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdVolverActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //prov0 es el proveedor de nombre "Sin especificar"
        Proveedor prov0 = new ProveedoresDao().traerProveedor(0);

        //Actualizo los articulos
        for (int x = 0; x < arts.size(); x++) {
            lblArticulo.setText(arts.get(x).getNombre());
            barraProgreso.setValue(x+1);
            arts.get(x).setProveedor(prov0);
            new ArticulosDao().actualizaArticulo(arts.get(x));
        }
        
        //Elimino el proveedor
        new ProveedoresDao().eliminarProveedor(provElim);
        lblArticulo.setText("Proveedor eliminado");
        lblCarga.setVisible(false);
        cmdVolver.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminandoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminandoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminandoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminandoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                eliminandoProveedor dialog = new eliminandoProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgreso;
    public static javax.swing.JButton cmdVolver;
    public static javax.swing.JLabel lblArticulo;
    public static javax.swing.JLabel lblCarga;
    // End of variables declaration//GEN-END:variables
}
